### PR TITLE
Post cover images

### PR DESCRIPTION
**Pull request by stevelacey**
Not ready to merge, but a start on #20, I'm using it in production.
- [x] Scripting
- [x] Styling
- [x] Scroll-based transition
- [x] Down (to content) arrow link
- [x] Trigger `$pBody.find('p:first img:only-child')`
     (other options: Tag? ID/Class wrapping image in content?)
- [x] Author + tags at top left?
- [x] Read time at top right? #110
- [ ] Fig caption / photo reference bottom right?
- [x] No-image fallback
- [x] No-js fallback - it just works™
- [x] Read time
- [x] ~~`-webkit-filter: blur`?~~ - ugly, unperformant
- [x] Allow `post-meta-bar` and menu link to follow the scroll out of sight (revealed on any scroll up), ala Medium
- [x] Fix issue with drawer on no-image articles
- [x] Respond `.post-meta-bar` on small screens
- [ ] Remove `.post-side`/`.post-author`? Is it necessary? Medium doesn't have it, and it no longer sits alongside the header on no-image posts, looks weird
- [x] Share button in exchange of bookmark button Medium has?
- [ ] Grab likes/RTs from somewhere (Twitter?) to show faces ala Medium

**Demo:** http://blog.stevelacey.net/streamlining-your-streaming-build-system

### CODE REVIEW

**Comment by Ardakilic** [comment]
+1, I was wondering the same.

**Comment by lyfeyaj** [comment]
+1

**Comment by stevelacey** [comment]
I have brought my fork up to date at https://github.com/stevelacey/ghostium – if you have issues/PRs that are still relevent, push them there – and we can see what we can do about them; I'll merge things! :)

**Comment by Ardakilic** [comment]
@stevelacey Thanks, your effort is much appreciated :)

**Comment by lyfeyaj** [comment]
@stevelacey  many thanks!!!

**Comment by lance0** [comment]
thanks @stevelacey

**Comment by oswaldoacauan** [comment]
Just an update:
I'm not using Ghost anymore and thats why I'm not updating this theme anymore but since a lot of people like it and still using it I will try to update and make it compatible with the latest version of Ghost on my vacation time, after that I will not add new features nor fix any bugs or update the theme by myself.

If someone is willing to continue the project and support new features and releases, you can contact me and I will give you permission to collaborate in the repository.

**Comment by stevelacey** [comment]
@oswaldoacauan I still use this, feel free to grant me contributor access.

**Comment by oswaldoacauan** [comment]
Done @stevelacey.

**Comment by igregma** [comment]
Great News @oswaldoacauan :-)
Looking forward for an update of the theme!!

**Comment by lance0** [comment]
This is the greatest theme for ghost, bar none.

**Comment by stevelacey** [comment]
@oswaldoacauan I don't appear to be able to close issues/prs, not sure what you've granted me but I'd need that

**Comment by oswaldoacauan** [comment]
@stevelacey you need to accept the invite https://github.com/oswaldoacauan/ghostium/invitations

**Comment by stevelacey** [comment]
@oswaldoacauan ah, evidently I don't get an email notification for that… thanks!

**Comment by igregma** [comment]
...wondering if there are new plans for an update @oswaldoacauan ?

**Comment by stevelacey** [comment]
@igregma I plan to set up another blog pretty soon and when I do I will think about resolving this mess – sorry that the plan isn't more concrete than that – but PR's and more than welcome.

**Comment by lance0** [comment]
Sounds good - I plan on helping out.

**Pull request closed without merging**
