### PR TITLE
updates for newest ghost engine (1.6.2)

### PR DESCRIPTION
**Pull request by sideris**

### CODE REVIEW

**Comment by sideris** [comment]
This is the 4th exactly similar PR for this, seems there's demand for this theme.

**Comment by Gcampes** [comment]
Hi, Could you revert the `partials/custom/navigation.hbs` and bump the version?

**Comment by sideris** [comment]
@Gcampes Hi. Sure! Will do.

**Comment by sideris** [comment]
@Gcampes Is that fine now?

**Comment by oswaldoacauan** [comment]
Closed in favor of #187

**Pull request closed without merging**
