### PR TITLE
Sync the theme with the latest changes from the Ghost 1.0 release.

### PR DESCRIPTION
**Pull request by dmakkuni**

### CODE REVIEW

**Comment by joren** [comment]
I assume `sh.exe.stackdump` should not have been committed. But 👍 on making these changes.

**Comment by dmakkuni** [comment]
@joren Correct, missed that one. I've have pushed another commit to eliminate it from my working branch.

**Comment by mtothed** [comment]
ah missed this pull request and did these changes on my fork.
don't forget to merge 👍

**Comment by oswaldoacauan** [comment]
Closed in favor of #187

**Pull request closed without merging**
