### PR TITLE
Added MathJax integration

### PR DESCRIPTION
**Pull request by bIgBV**
Wanted to render Latex equations on myblog, integrated MathJax borrowing from this [blog here](http://feynmanliang.com/mathjax-integration/).

If there were any mistakes please do tell me, this is my first Pull request.

### CODE REVIEW

**Comment by bIgBV** [comment]
I tested this on my own blog here : http://voletibhargav.me/simple-sorting-algorithms-insertion-sort/

**Comment by maurizzzio** [comment]
Hi @bIgBV, unfortunately your fix works whenever the page is rendered as a whole (like the one you have in your blog), however ghostium uses https://github.com/defunkt/jquery-pjax to load a page without doing a browser reload so it'll only work if there's a post opened and only for the first time

ghostium

To fix the problem you have to actually tell MathJax to re-render any latex like syntax every time a page is rendered, the hook needs to be in `src/scripts`

```javascript
function _mathJaxSupport() {
  MathJax.Hub.Queue(['Typeset', MathJax.Hub]);
}

// PJax bindings
// =================
if ($.support.pjax && GHOSTIUM.enablePjax) {
  $document.on('pjax:start', function() {
    $surface.scrollTop(0);
  });

  $document.on('pjax:end', function() {
    _disqusHandler();
    _gaHandler();
    _disqusCounterHandler();
    _prismHandler();
    _mathJaxSupport();

    $('[data-load-image]', $content).each(function() {
      ImageLoader.load($(this));
    });
  });

  var _pjaxOptions = {
    container: '[data-pjax-container]',
    fragment: '[data-pjax-container]'
  };

  $document.pjax('a[data-pjax]', _pjaxOptions);

  $document.on('submit', 'form[data-pjax]', function(e) {
    $.pjax.submit(e, _pjaxOptions);
  });
}
```

Note that I'm invoking `_mathJaxSupport()` every time the plugin fires the `pjax:end` event

The fix doesn't end here since the production files need to be updated, I did the following:
(:warning:  WARNING: doing so will replace the contents of most of the generated stuff, make a backup of the local copy of the theme you have)

- first of all run `npm install` on the theme
- edit the contents of the `src` folder (don't edit `assets/` or `partials/` directly since they're likely to be overwritten)
- run `grunt dryrun`
- commit and push the newly generated production files to your server

Proof:

ghostium-after-fix

**Comment by oswaldoacauan** [comment]
I dont think is a good ideia to have MathJax included OOTB.

Maybe we can add a "how to" page to explain how to add mathajx.

**Comment by bIgBV** [comment]
@maurizzzio thanks for that, I wasn't actually very sure of how to fix that :+1: .

PS: Sorry for the extremely late reply.

**Pull request closed without merging**
