### PR TITLE
Update to work with Ghost v1.21.x

### PR DESCRIPTION
**Pull request by code0100fun**

### CODE REVIEW

**Comment by alastairtree** [comment]
I just used this PR and it works well on ghost.io. Thanks.

**Comment by jaggerwang** [comment]
Can anyone merge this branch?

**Comment by hao-lee** [comment]
@jaggerwang Just use code0011fun's [branch](https://github.com/code0100fun/ghostium/tree/v1-22-x).

**Comment by hao-lee** [comment]
@oswaldoacauan Hi, thanks for your hard work. I know maintaining an open source project needs a lot of energy. Maybe you can create a new organization and add some contributor to help you to develop this project. Ghostium is the most popular Ghost theme on GitHub even it is not very active now. We don't want to see it is abandoned.

**Pull request merged**
